name: Update

on:
  workflow_dispatch:
  schedule:
  - cron: "40 1,3,5,7,9,11,13,15,17,19,21,23 * * *"

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install --user -r requirements.txt
      - run: git config user.name github-actions && git config user.email github-actions[bot]@users.noreply.github.com
      - run: ./scan.py
      - run: git add archives/ && git commit -m 'Updating zone information' && git push
